### ISSUE TITLE
Skill no reproduce

### ISSUE THREAD

**Issue by jmcastillejo** [Oliv3rs/Alexa-Skills#1]
Hola,

Ante todo agradecer tu trabajo, ayudando a los que estamos iniciando en el mundo de las skills de Alexa.

Te escribo porque he seguido tus pasos pero no logro reproducir audio de mi stream 

https://aruba.soundcast.me/stream

Es un servidor seguro Icecast. 

Un saludo

**Comment by Oliv3rs** [comment]
Hola, Amazon pide que la terminación de tu URL
AAC/MP4, MP3, PLS, M3U/M3U8, o HLS.

Aquí la documentación de Amazon:

Audio file must be hosted at an Internet-accessible HTTPS endpoint on port 443.

The web server must present a valid and trusted SSL certificate. Self-signed certificates are not allowed. Many content hosting services provide this. For example, you could host your files at a service such as Amazon Simple Storage Service (Amazon S3)<https://aws.amazon.com/s3/> (an Amazon Web Services<http://aws.amazon.com/> offering).

If the stream is a playlist container that references additional streams, each stream within the playlist must also be hosted at an Internet-accessible HTTPS endpoint on 443 with a valid and trusted SSL certificate.

The supported formats for the audio file include AAC/MP4, MP3, PLS, M3U/M3U8, and HLS. Bitrates: 16kbps to 384 kbps.

Saludos.
Oliver González

________________________________

**Comment by jmcastillejo** [comment]
era lo que has apuntado, muchas gracias!!!
